In [1]:
import pandas as pd
import json

In [ ]:
cells_file = './results/gigatime/cells/cells.csv'
cells = pd.read_csv(cells_file, sep=',', index_col=0, header=0)
cells

,DAPI,TRITC,Cy5,PD-1,CD14,CD4,T-bet,CD34,CD68,CD16,...,CD3,CD8,PD-L1,CK,Ki67,Tryptase,Actin-D,Caspase3-D,PHH3-B,Transgelin
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154980,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
154981,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
154982,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
154983,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
154984,True,True,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [3]:
cells = cells.loc[cells['DAPI']]
cells

,DAPI,TRITC,Cy5,PD-1,CD14,CD4,T-bet,CD34,CD68,CD16,...,CD3,CD8,PD-L1,CK,Ki67,Tryptase,Actin-D,Caspase3-D,PHH3-B,Transgelin
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
6,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154978,True,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
154979,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
154980,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
154981,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
154984,True,True,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
positive_markers = {
    'T': ['CD3'],
    'CD8+ T': ['CD8', 'CD3'],
    'CD4+ T': ['CD4', 'CD3'],
    'NK': ['CD16'],
    'B': ['CD20'],
    'Plasma': ['CD138'],
    'Monocyte': ['CD14'],
    'Macrophage': ['CD68'],
    'DC': ['CD11c'],
    'Mast': ['Tryptase'],
    'Fibroblasts': ['Transgelin'],
    'Myofibroblast': ['Transgelin', 'Actin-D'],
    'Epithelial': ['CK'],
    'Endothelial': ['CD34'],
}
cell_types = pd.DataFrame(index=cells.index)
for cell_type, markers in positive_markers.items():
    cell_types[cell_type] = cells[markers].all(axis=1)
cell_types

,T,CD8+ T,CD4+ T,NK,B,Plasma,Monocyte,Macrophage,DC,Mast,Fibroblasts,Myofibroblast,Epithelial,Endothelial
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154978,False,False,False,False,False,False,False,True,False,False,False,False,False,False
154979,False,False,False,False,False,False,False,False,False,False,False,False,False,False
154980,False,False,False,False,False,False,False,False,False,False,False,False,False,False
154981,False,False,False,False,False,False,False,False,False,False,False,False,False,False
154984,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [5]:
cell_types['cell_type'] = None
cell_types.loc[cell_types['T'], 'cell_type'] = 'T'
cell_types.loc[cell_types['CD4+ T'], 'cell_type'] = 'CD4+ T'
cell_types.loc[cell_types['NK'], 'cell_type'] = 'NK'
cell_types.loc[cell_types['B'], 'cell_type'] = 'B'
cell_types.loc[cell_types['Plasma'], 'cell_type'] = 'Plasma'
cell_types.loc[cell_types['Monocyte'], 'cell_type'] = 'Monocyte'
cell_types.loc[cell_types['Macrophage'], 'cell_type'] = 'Macrophage'
cell_types.loc[cell_types['DC'], 'cell_type'] = 'DC'
cell_types.loc[cell_types['Mast'], 'cell_type'] = 'Mast'
cell_types.loc[cell_types['Fibroblasts'], 'cell_type'] = 'Fibroblasts'
cell_types.loc[cell_types['Myofibroblast'], 'cell_type'] = 'Myofibroblast'
cell_types.loc[cell_types['Epithelial'], 'cell_type'] = 'Epithelial'
cell_types.loc[cell_types['Endothelial'], 'cell_type'] = 'Endothelial'
cell_types_unique = cell_types.loc[:, ~cell_types.columns.isin(['CD8+ T', 'CD4+ T', 'Myofibroblast', 'cell_type'])]
cell_types.loc[cell_types_unique.sum(axis=1) != 1, 'cell_type'] = 'Unknown'
cell_types['cell_type'].value_counts()

cell_type
Unknown          52322
Epithelial       23170
Endothelial       1382
CD4+ T             729
T                  504
Fibroblasts        372
Plasma              66
Myofibroblast       55
Macrophage          32
Monocyte            29
DC                   1
Name: count, dtype: int64

In [ ]:
nucleus_seg_json_file = './data/align_he.json'

with open(nucleus_seg_json_file, 'r') as f:
    nucleus_seg_dict = json.load(f)

In [11]:
l = []
for i in cell_types.index:
    try:
        cell_types.loc[i, 'x'] = nucleus_seg_dict['nuc'][str(i)]['centroid'][0]
        cell_types.loc[i, 'y'] = nucleus_seg_dict['nuc'][str(i)]['centroid'][1]
    except:
        l.append(i)
cell_types

,T,CD8+ T,CD4+ T,NK,B,Plasma,Monocyte,Macrophage,DC,Mast,Fibroblasts,Myofibroblast,Epithelial,Endothelial,cell_type,x,y
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,Unknown,218.817778,1392.555556
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Epithelial,334.379791,1392.212544
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,Unknown,132.343373,1410.707831
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False,Epithelial,5686.331572,1419.505945
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,Unknown,7956.642466,1432.569863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154978,False,False,False,False,False,False,False,True,False,False,False,False,False,False,Macrophage,21595.000000,16388.155556
154979,False,False,False,False,False,False,False,False,False,False,False,False,False,False,Unknown,22222.078125,16389.109375
154980,False,False,False,False,False,False,False,False,False,False,False,False,False,False,Unknown,21436.850000,16389.050000
154981,False,False,False,False,False,False,False,False,False,False,False,False,False,False,Unknown,21497.294118,16389.294118
154984,False,False,False,False,False,False,False,False,False,False,False,False,False,True,Endothelial,36606.440586,16409.750772

In [ ]:
cell_types.to_csv('./results/gigatime/cell_types/cell_types.csv')
cell_types[['x', 'y', 'cell_type']].to_csv('./results/gigatime/results.csv')